<a href="https://colab.research.google.com/github/waraporn19/Project_2021_matchingcolor/blob/main/newD5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
 import pandas as pd
 import numpy as np

In [3]:
from google.colab import drive 
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
path = '/content/drive/My Drive/shadeimg'

In [5]:
import os

In [6]:
os.listdir(path)

['รูปฟัน07',
 '9-10 7 2021',
 '11 7 2021',
 'ฟันสักอย่างจำวันไม่ได้',
 '1 teeth .gsheet',
 '16 8 2021',
 '17 8 2021',
 '1 teeth .xlsx',
 '2 teeth .xlsx',
 '2 teeth.gsheet',
 'All shade',
 'A1set1.xlsx',
 'SVM shade',
 'BB1.xlsx',
 'CC1.xlsx',
 'DD1.xlsx',
 'AA1.xlsx',
 'Color-checkerDD .xlsx',
 'Color-checkerAA1.xlsx',
 'Color-checkerBB.xlsx',
 'Color-checkerCC.xlsx']

In [7]:
!pip install azure-storage-blob==2.1.0

Collecting azure-storage-blob==2.1.0
  Downloading azure_storage_blob-2.1.0-py2.py3-none-any.whl (88 kB)
     |████████████████████████████████| 88 kB 3.4 MB/s
Collecting azure-storage-common~=2.1
  Downloading azure_storage_common-2.1.0-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 3.9 MB/s
Collecting azure-common>=1.1.5
  Downloading azure_common-1.1.28-py2.py3-none-any.whl (14 kB)
Collecting cryptography
  Downloading cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 33.6 MB/s
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from azure-storage-common~=2.1->azure-storage-blob==2.1.0) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from azure-storage-common~=2.1->azure-storage-blob==2.1.0) (2.23.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography->azure-storage-common~=2.1->azure-storage-blob==2.1.0) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography->azure-storage-common~=2.1->azure-storage-blob==2.1.0) (2.21)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil->azure-storage-common~=2.1->azure-storage-blob==2.1.0) (1.15.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->azure-storage-common~=2.1->azure-storage-blob==2.1.0) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->azure-storage-common~=2.1->azure-storage-blob==2.1.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->azure-storage-common~=2.1->azure-storage-blob==2.1.0) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->azure-storage-common~=2.1->azure-storage-blob==2.1.0) (2.10)
Installing collected packages: cryptography, azure-common, azure-storage-common, azure-storage-blob
Successfully installed azure-common-1.1.28 azure-storage-blob-2.1.0 azure-storage-common-2.1.0 cryptography-36.0.1

In [8]:
from azure.storage.blob import BlockBlobService
import os

In [9]:
blob_service_client = BlockBlobService(account_name='dent01', account_key='CuShY0B4TZJ84TjzPpaHxyrHOpO73aGXeCpdVq7x26OjIlQ1HOz+3DVc9pDEj9BdcEL8odFuTRF0mOAE+aCgiw==')

In [10]:
import cv2
from matplotlib import pyplot as plt #การเรียกใช้คำสั่ง matplotlib เพื่อวาดกราฟ โดยแทนชื่อ matplotlib ด้วย plt
import matplotlib

In [11]:
AA = os.path.join(path,'AA1.xlsx')

In [12]:
A1_set1= pd.read_excel(AA, sheet_name='A1Set1')
A1_set1

                               ชื่อไฟล์ข้อมูล  ...                   หมายเหตุ
0    1665B5AE-934F-4116-AE19-3369544A125F.png  ...  ค่า duration 1/90 ISO 171
1    47C127AF-8872-4A1E-9F72-082F72252B3F.png  ...  ค่า duration 1/90 ISO 171
2    15991304-7501-4377-BE6E-1B9AF5258FC1.png  ...  ค่า duration 1/90 ISO 171
3    5CE2CB9A-C765-4240-B3D3-E352B1581A1B.png  ...  ค่า duration 1/90 ISO 171
4    26A32C19-6890-4999-A7F2-D8399A56E3B5.png  ...  ค่า duration 1/90 ISO 171
..                                        ...  ...                        ...
155  A95B5685-7346-4585-AE3D-674F5539C891.png  ...  ค่า duration 1/90 ISO 171
156  548D8FC6-5993-476E-9F84-FEEE003BE798.png  ...  ค่า duration 1/90 ISO 171
157  761A1FDE-FD1C-4A18-8C5F-27608736CB3C.png  ...  ค่า duration 1/90 ISO 171
158  027B3600-F7AD-41B8-8DE5-1706B68BAE4F.png  ...  ค่า duration 1/90 ISO 171
159  57148CAB-1038-4B0D-9C2F-6DCB9632D2DF.png  ...  ค่า duration 1/90 ISO 171

[160 rows x 7 columns]

In [13]:
A1_set1.rename(columns={"ฝั่งซ้าย": "Ref"},inplace=True)

In [14]:
A1_set1.rename(columns={"ฝั่งขวา":"Shad"},inplace=True)

In [15]:
A1_set1.rename(columns={"ชื่อไฟล์ข้อมูล":"Img"},inplace=True)

In [16]:
A1_set1

                                          Img  ...                   หมายเหตุ
0    1665B5AE-934F-4116-AE19-3369544A125F.png  ...  ค่า duration 1/90 ISO 171
1    47C127AF-8872-4A1E-9F72-082F72252B3F.png  ...  ค่า duration 1/90 ISO 171
2    15991304-7501-4377-BE6E-1B9AF5258FC1.png  ...  ค่า duration 1/90 ISO 171
3    5CE2CB9A-C765-4240-B3D3-E352B1581A1B.png  ...  ค่า duration 1/90 ISO 171
4    26A32C19-6890-4999-A7F2-D8399A56E3B5.png  ...  ค่า duration 1/90 ISO 171
..                                        ...  ...                        ...
155  A95B5685-7346-4585-AE3D-674F5539C891.png  ...  ค่า duration 1/90 ISO 171
156  548D8FC6-5993-476E-9F84-FEEE003BE798.png  ...  ค่า duration 1/90 ISO 171
157  761A1FDE-FD1C-4A18-8C5F-27608736CB3C.png  ...  ค่า duration 1/90 ISO 171
158  027B3600-F7AD-41B8-8DE5-1706B68BAE4F.png  ...  ค่า duration 1/90 ISO 171
159  57148CAB-1038-4B0D-9C2F-6DCB9632D2DF.png  ...  ค่า duration 1/90 ISO 171

[160 rows x 7 columns]

In [17]:
#A1_set1 = A1_set1.drop([0])
#A1_set1

In [18]:
table1= A1_set1[['Ref', 'Shad','Img']]
table1

    Ref Shad                                       Img
0    A1   A1  1665B5AE-934F-4116-AE19-3369544A125F.png
1    A1   A1  47C127AF-8872-4A1E-9F72-082F72252B3F.png
2    A1   A1  15991304-7501-4377-BE6E-1B9AF5258FC1.png
3    A1   A1  5CE2CB9A-C765-4240-B3D3-E352B1581A1B.png
4    A1   A1  26A32C19-6890-4999-A7F2-D8399A56E3B5.png
..   ..  ...                                       ...
155  A1   D4  A95B5685-7346-4585-AE3D-674F5539C891.png
156  A1   D4  548D8FC6-5993-476E-9F84-FEEE003BE798.png
157  A1   D4  761A1FDE-FD1C-4A18-8C5F-27608736CB3C.png
158  A1   D4  027B3600-F7AD-41B8-8DE5-1706B68BAE4F.png
159  A1   D4  57148CAB-1038-4B0D-9C2F-6DCB9632D2DF.png

[160 rows x 3 columns]

In [19]:
table1= A1_set1[['Ref', 'Shad','Img']]
table1

    Ref Shad                                       Img
0    A1   A1  1665B5AE-934F-4116-AE19-3369544A125F.png
1    A1   A1  47C127AF-8872-4A1E-9F72-082F72252B3F.png
2    A1   A1  15991304-7501-4377-BE6E-1B9AF5258FC1.png
3    A1   A1  5CE2CB9A-C765-4240-B3D3-E352B1581A1B.png
4    A1   A1  26A32C19-6890-4999-A7F2-D8399A56E3B5.png
..   ..  ...                                       ...
155  A1   D4  A95B5685-7346-4585-AE3D-674F5539C891.png
156  A1   D4  548D8FC6-5993-476E-9F84-FEEE003BE798.png
157  A1   D4  761A1FDE-FD1C-4A18-8C5F-27608736CB3C.png
158  A1   D4  027B3600-F7AD-41B8-8DE5-1706B68BAE4F.png
159  A1   D4  57148CAB-1038-4B0D-9C2F-6DCB9632D2DF.png

[160 rows x 3 columns]

In [20]:
A1_set11 =A1_set1.head(3)
A1_set11

                                        Img  ...                   หมายเหตุ
0  1665B5AE-934F-4116-AE19-3369544A125F.png  ...  ค่า duration 1/90 ISO 171
1  47C127AF-8872-4A1E-9F72-082F72252B3F.png  ...  ค่า duration 1/90 ISO 171
2  15991304-7501-4377-BE6E-1B9AF5258FC1.png  ...  ค่า duration 1/90 ISO 171

[3 rows x 7 columns]

In [21]:
list_total1 = list()
for img in A1_set11['Img']:
  S1_double = img
  full_path_to_file2 = os.path.join(S1_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imgS1_A1A1_1  = cv2.imread(S1_double) #RGB
  S1RGB_imgA1A1_1= cv2.cvtColor(imgS1_A1A1_1, cv2.COLOR_BGR2RGB)
  S1meanrefA1_1 = list()
  for i in range(S1RGB_imgA1A1_1.shape[0]): 
     for j in range(S1RGB_imgA1A1_1.shape[1]): 
                if 1769<i<1881 and 2019<j<2131 :
                  S1meanrefA1_1.append(S1RGB_imgA1A1_1[i][j]) 
  S1meanrefA1_1 = np.array(S1meanrefA1_1)
  S1rgbrefA1_1 = list()
  for i in range(3):
    S1rgbrefA1_1.append(S1meanrefA1_1[:,i].mean())
  list_total1.append(S1rgbrefA1_1)

In [29]:
list_total1

[[239.26191055920785, 226.7721775829884, 193.5400535670806],
 [238.4326759191624, 226.12490869247625, 192.41555068582096],
 [238.7831344858372, 226.52520087655222, 193.02548494440387]]

In [22]:
all_total = list()
for img in A1_set11['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)#RGB
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1770:1881,2020:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1771:1880,2016:2145]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(111*111, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  all_total.append(list_total)

In [23]:
cols=['R-ref', 'G-ref' , 'B-ref', 'R-Shad', 'G-Shad', 'B-Shad']
S1=pd.DataFrame(all_total,columns=cols)
S1['Setting']='Set1'
S1

        R-ref       G-ref       B-ref  ...      G-Shad      B-Shad  Setting
0  239.261911  226.772178  193.540054  ...  227.425574  194.950928     Set1
1  238.432676  226.124909  192.415551  ...  226.726477  193.791053     Set1
2  238.783134  226.525201  193.025485  ...  227.131072  194.443994     Set1

[3 rows x 7 columns]

In [ ]:
[[239.26191055920785, 226.7721775829884, 193.5400535670806],
 [238.4326759191624, 226.12490869247625, 192.41555068582096],
 [238.7831344858372, 226.52520087655222, 193.02548494440387]]

In [24]:
all_total = list()
for img in A1_set11['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2HSV)#HSV
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1770:1881,2020:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1771:1880,2016:2145]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  all_total.append(list_total)

In [25]:
cols=['H-ref', 'S-ref' , 'V-ref', 'H-Shad', 'S-Shad', 'V-Shad']
S2=pd.DataFrame(all_total,columns=cols)
S2['Setting']='Set1'
S2

       H-ref      S-ref       V-ref     H-Shad     S-Shad      V-Shad Setting
0  21.848389  48.820144  239.261911  21.788351  47.702439  239.680321    Set1
1  22.034413  49.293320  238.432676  21.958893  48.209231  238.840410    Set1
2  21.989205  48.946108  238.783134  21.892611  47.829457  239.209800    Set1

#Datapoint 1

In [26]:
data_1R = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)#RGB
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1770:1881,2020:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1771:1882,2016:2127]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(111*111, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_1R.append(list_total)

In [27]:
cols=['R-ref', 'G-ref' , 'B-ref', 'R-Shad', 'G-Shad', 'B-Shad']
t1=pd.DataFrame(data_1R,columns=cols)
t1['Setting']='Set1'
t1

          R-ref       G-ref       B-ref  ...      G-Shad      B-Shad  Setting
0    239.261911  226.772178  193.540054  ...  226.201364  192.489327     Set1
1    238.432676  226.124909  192.415551  ...  225.552634  191.392582     Set1
2    238.783134  226.525201  193.025485  ...  225.945134  191.984173     Set1
3    238.943430  226.796039  192.905771  ...  226.221329  191.881503     Set1
4    238.848145  226.354679  192.963720  ...  225.789709  191.916728     Set1
..          ...         ...         ...  ...         ...         ...      ...
155  234.991397  215.878094  165.114601  ...  215.150475  164.009658     Set1
156  235.865514  216.421557  166.558315  ...  215.787598  165.457674     Set1
157  231.620161  212.385439  163.487947  ...  211.654330  162.344371     Set1
158  235.459541  216.324974  165.122717  ...  215.679166  164.034900     Set1
159  235.604172  216.610178  164.848389  ...  215.983199  163.806185     Set1

[160 rows x 7 columns]

In [ ]:
data_1H = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2HSV)#HSV
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1770:1881,2020:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1771:1880,2016:2145]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(109*129, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_1H.append(list_total)

In [ ]:
cols=['H-ref', 'S-ref' , 'V-ref', 'H-Shad', 'S-Shad', 'V-Shad']
t11=pd.DataFrame(data_1H,columns=cols)
t11['Setting']='Set1'
t11

In [ ]:
dp1 = pd.concat([t1,t11,table1], axis=1)
dp1

#Datapoint 2

In [ ]:
data_2R = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)#RGB
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1720:1821,2030:2141]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1710:1821,1720:1831]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(111*111, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_2R.append(list_total)

In [ ]:
data_2R = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)#RGB
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1720:1821,2030:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1710:1811,1720:1821]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(101*101, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(101*101, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_2R.append(list_total)

In [ ]:
cols=['R-ref', 'G-ref' , 'B-ref', 'R-Shad', 'G-Shad', 'B-Shad']
t2=pd.DataFrame(data_2R,columns=cols)
t2['Setting']='Set1'
t2

In [ ]:
data_2H = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2HSV)#HSV
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1720:1821,2030:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1710:1811,1720:1821]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(101*101, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(101*101, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_1H.append(list_total)

In [ ]:
cols=['H-ref', 'S-ref' , 'V-ref', 'H-Shad', 'S-Shad', 'V-Shad']
t22=pd.DataFrame(data_2H,columns=cols)
t22['Setting']='Set1'
t22

In [ ]:
dp2 = pd.concat([t2,t22,table1], axis=1)
dp2

#Datapoint 3

In [ ]:
den10= cv2.rectangle(RGB_img1,(2030,1840),(2130,1740),(255,0,0),10) 
Square1 = cv2.rectangle(RGB_img1,(1710,1740),(1810,1840),(255,0,0),10)#(x,y)(x,y)
plt.imshow(RGB_img1)

In [ ]:
data_3R = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)#RGB
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1740:1841,2030:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1710:1811,1740:1841]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(101*101, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(101*101, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_3R.append(list_total)

In [ ]:
cols=['R-ref', 'G-ref' , 'B-ref', 'R-Shad', 'G-Shad', 'B-Shad']
t3=pd.DataFrame(data_3R,columns=cols)
t3['Setting']='Set1'
t3

In [ ]:
data_3H = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2HSV)#HSV
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1740:1841,2030:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1710:1811,1740:1841]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(101*101, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(101*101, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_3H.append(list_total)

In [ ]:
cols=['H-ref', 'S-ref' , 'V-ref', 'H-Shad', 'S-Shad', 'V-Shad']
t33=pd.DataFrame(data_3H,columns=cols)
t33['Setting']='Set1'
t33

In [ ]:
dp3 = pd.concat([t3,t33,table1], axis=1)
dp3

#Datapoint 4

In [ ]:
den10= cv2.rectangle(RGB_img1,(2030,1860),(2130,1760),(255,0,0),10) 
Square1 = cv2.rectangle(RGB_img1,(1710,1760),(1810,1860),(255,0,0),10)#(x,y)(x,y)
plt.imshow(RGB_img1)

In [ ]:
data_4R = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)#RGB
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1760:1861,2030:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1760:1861,1710:1811]  
  S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
  S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(109*129, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_4R.append(list_total)

In [ ]:
cols=['R-ref', 'G-ref' , 'B-ref', 'R-Shad', 'G-Shad', 'B-Shad']
t4=pd.DataFrame(data_4R,columns=cols)
t4['Setting']='Set1'
t4

In [ ]:
data_4H = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2HSV)#HSV
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1770:1881,2020:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1771:1880,2016:2145]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(109*129, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_4H.append(list_total)

In [ ]:
cols=['H-ref', 'S-ref' , 'V-ref', 'H-Shad', 'S-Shad', 'V-Shad']
t44=pd.DataFrame(data_4H,columns=cols)
t44['Setting']='Set1'
t44

In [ ]:
dp4 = pd.concat([t4,t44,table1], axis=1)
dp4

#Datapoint 5

In [ ]:
data_5R = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)#RGB
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1770:1881,2020:2131]  1779<i<1879 and 2029<j<2134 :
  S5meanA1_2 = S5RGB_imgA1A1_1[1771:1880,2016:2145]  1779<i<1879 and 1709<j<1819 :
  S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(109*129, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_5R.append(list_total)

In [ ]:
cols=['R-ref', 'G-ref' , 'B-ref', 'R-Shad', 'G-Shad', 'B-Shad']
t5=pd.DataFrame(data_5R,columns=cols)
t5['Setting']='Set1'
t5

In [ ]:
data_5H = list()
for img in A1_set1['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2HSV)#HSV
  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1770:1881,2020:2131]  
  S5meanA1_2 = S5RGB_imgA1A1_1[1771:1880,2016:2145]
  S5refA1_1 = np.reshape(S5meanrefA1_1,(111*111, 3))
  S5refA1_2 = np.reshape(S5meanA1_2,(109*129, 3))
  S5refA1_3 = np.array(S5refA1_1)
  S5refA1_4 = np.array(S5refA1_2)
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()

  list_total = list()
  list_total.append(Rref)
  list_total.append(Gref)
  list_total.append(Bref)
  list_total.append(R)
  list_total.append(G)
  list_total.append(B)
  data_5H.append(list_total)

In [ ]:
cols=['H-ref', 'S-ref' , 'V-ref', 'H-Shad', 'S-Shad', 'V-Shad']
t55=pd.DataFrame(data_5H,columns=cols)
t55['Setting']='Set1'
t55

In [ ]:
dp5= pd.concat([t5,t55,table1], axis=1)
dp5

In [ ]:
st1= pd.concat([dp1, dp2,dp3,dp4,dpP5], axis=0)
st1

In [ ]:
st1.to_csv('D3set5.csv', index=False)